### ISSUE TITLE
Fature[Result] in method getOrder in HomeController

### ISSUE THREAD

**Issue by fpscala** [Prince951-17/cleaning#11]

**Comment by fpscala** [comment]
![image](https://user-images.githubusercontent.com/37735368/59009768-67ae2680-8848-11e9-8c3d-240bf2fad382.png)

**Comment by behruz-b** [comment]
fixed by [commit](https://github.com/Prince951-17/cleaning/commit/8af88c0a03ccd4280c93686070656eccc7354722)
